version: '3.8'
name: 'nextjs_ts_blog'
services:
  node:
    container_name: nextjs_ts_blog
    hostname: ts_blog
    build: . 
    image: nodejs:18.14.2-r0
    volumes:
    - ../:/root
    ports:
      - 3000:3000
    working_dir: /root
    tty: true
#    command: ["bash", "--login"]
